### ISSUE TITLE
Error when saving BruteForce layer to use by TensorFlow Serving

### ISSUE THREAD

**Issue by cfregly** [tensorflow/recommenders#131]
Following the quickstart, i'm trying to save the BruteForce model to use by TensorFlow Serving.  The goal is to pass a `user_id` to TensorFlow Serving endpoint and return a list of `movie_title`s

```
...
index = tfrs.layers.ann.BruteForce(model.user_model)
index.save(tensorflow_saved_model_path_bruteforce_model, save_format='tf')
```

```
ValueError: Model <tensorflow_recommenders.layers.ann.BruteForce object at 0x7f6e9c2aa7b8> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`.
```

I tried explicitly calling index.build(1), etc, but this is leading to more errors.

(This is a continuation of [this](https://github.com/tensorflow/recommenders/issues/129#issuecomment-718103510) thread...)

**Comment by cfregly** [comment]
After running the following prediction, i can save the model.
```
# Get some recommendations.
_, titles = index(np.array(["42"]))

print(f"Top 3 recommendations for user 42: {titles[0, :3]}")
```

however, i'm seeing this error when i check the signature with `saved_model_cli`:

```
2020-10-28 18:55:56.487371: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_1'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_input_1:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: StatefulPartitionedCall:0
    outputs['output_2'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 10)
        name: StatefulPartitionedCall:1
  Method name is: tensorflow/serving/predict
2020-10-28 18:55:58.819598: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-28 18:55:58.850169: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-10-28 18:55:58.850206: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-16-36-168): /proc/driver/nvidia/version does not exist
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/tools/saved_model_cli.py", line 1185, in main
    args.func(args)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/tools/saved_model_cli.py", line 715, in show
    _show_all(args.dir)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/tools/saved_model_cli.py", line 307, in _show_all
    _show_defined_functions(saved_model_dir)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/tools/saved_model_cli.py", line 187, in _show_defined_functions
    trackable_object = load.load(saved_model_dir)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 603, in load
    return load_internal(export_dir, tags, options)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 633, in load_internal
    ckpt_options)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 131, in __init__
    self._restore_checkpoint()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 358, in _restore_checkpoint
    "%r from the checkpoint." % obj))
NotImplementedError: Missing functionality to restore state of object <tensorflow.python.saved_model.load._RestoredResource object at 0x7fc464176160> from the checkpoint.
```

**Comment by cfregly** [comment]
The SavedModel still seems to work, however:

```
saved_model_cli run --input_exprs 'input_1=[str(42)]' --tag_set serve --signature_def serving_default --dir $tensorflow_saved_model_path_bruteforce_model
```

```
Result for output key output_1:
[[3.9453535 2.9104383 2.7285933 2.6687438 2.5107827 2.4038887 2.3974428
  2.386409  2.321732  2.3211298]]
Result for output key output_2:
[[b'Rent-a-Kid (1995)' b'Last Dance (1996)'
  b'Adventures of Pinocchio, The (1996)'
  b'Winnie the Pooh and the Blustery Day (1968)'
  b'Aristocats, The (1970)' b'Celtic Pride (1996)'
  b'Conan the Barbarian (1981)' b'House Arrest (1996)'
  b'Just Cause (1995)' b'Johnny 100 Pesos (1993)']]
```

**Comment by maciejkula** [comment]
Off the top of my head:

1. Have you called `index` on the layer to give it candidates?
2. You need to call it at least once to make it saveable - there are other ways but this one is by far the most intuitive.
