### ISSUE TITLE
how to add recall@k metrics?

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/recommenders#183]
how to add recall@k metrics???

```
        self.retrieval_task = tfrs.tasks.Retrieval(
            metrics=tfrs.metrics.FactorizedTopK(
                candidates=total_items_dataset.batch(4096).map(self.item_model),
                metrics=
                [tf.keras.metrics.TopKCategoricalAccuracy(
                    k=x, name=f"{self.name}/top_{x}_categorical_accuracy")
                    for x in [1, 5, 10, 50, 100]] +
                [tf.keras.metrics.Recall(
                    top_k=x, name=f"top_{x}_recall")
                    for x in [1, 5, 10, 50, 100]]

            )
        )
```

error info:
```
Traceback (most recent call last):
  File "modeling.py", line 208, in <module>
    model.compile(optimizer=optimizer)
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/data/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (retrieval/concat_1:0) = ] [[0.00216801604 0.00680248 0.00661896868...]...] [y (retrieval/Cast_1/x:0) = ] [0]
	 [[{{node retrieval/assert_greater_equal/Assert/AssertGuard/else/_1/retrieval/assert_greater_equal/Assert/AssertGuard/Assert}}]]
	 [[retrieval/assert_less_equal/Assert/AssertGuard/pivot_f/_13/_129]]
  (1) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (retrieval/concat_1:0) = ] [[0.00216801604 0.00680248 0.00661896868...]...] [y (retrieval/Cast_1/x:0) = ] [0]
	 [[{{node retrieval/assert_greater_equal/Assert/AssertGuard/else/_1/retrieval/assert_greater_equal/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_3533]

Function call stack:
train_function -> train_function
```

**Comment by maciejkula** [comment]
In this instance, there is only one positive example for each query. AFAIK, in this case recall@k and top K categorical accuracy are the same.

**Comment by liyunrui** [comment]
> In this instance, there is only one positive example for each query. AFAIK, in this case recall@k and top K categorical accuracy are the same.

I think top k accuracy is precision@k, which is different from recall@k even TP+FN =1
