### ISSUE TITLE
tfrs.Model.summary() function got error

### ISSUE THREAD

**Issue by jasoncaojingren** [tensorflow/recommenders#253]
If follow the quick start guide,
https://www.tensorflow.org/recommenders/examples/quickstart

Define class MovieLensModel(tfrs.Model):
model = MovieLensModel(user_model, movie_model, task)

after compile and fit the model, if try to call model.summary() function, it will generate error.

**Comment by maciejkula** [comment]
When reporting an issue it's customary to include the actual error message - this really helps in figuring out what's gone wrong.

**Comment by jasoncaojingren** [comment]
Traceback (most recent call last):
  File "D:/TechBuilder/TensorFlow/Dev202103/tfrs/tfrs1.py", line 214, in <module>
    rs1()
  File "D:/TechBuilder/TensorFlow/Dev202103/tfrs/tfrs1.py", line 185, in rs1
    print("model summary", model.summary())
  File "D:\Apps\Python\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2376, in summary
    raise ValueError('This model has not yet been built. '
ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.

Process finished with exit code 1

**Comment by Flipper-afk** [comment]
You can try `model.user_model.summary()` or `model.movie_model.summary()`. It should then, output the parameters of each model. Hope that helps in a nutshell

**Comment by TimSchmeier** [comment]
you might need to run a batch of data through before calling `summary()`
