### ISSUE TITLE
v0.5.0: Cannot load Scann models

### ISSUE THREAD

**Issue by Ullar-Kask** [tensorflow/recommenders#297]
Hi,

Saving and loading a scann model from within the same python script works as expected:

```
path = os.path.join('.', file)
index.save(path, options=tf.saved_model.SaveOptions(namespace_whitelist=["Scann"]))
# reloading works:
loaded = tf.keras.models.load_model(path)
```

But reloading in a different script fails:

```
path = os.path.join('.', file)
index = tf.keras.models.load_model(path)
```

Throws exception:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 144, in load
    loaded = tf_load.load_partial(path, nodes_to_load, options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 765, in load_partial
    return load_internal(export_dir, tags, options, filters=filters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 892, in load_internal
    raise FileNotFoundError(
FileNotFoundError: Op type not registered 'Scann>TensorsToScann' in binary running on ip-172-31-31-29. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 If trying to load on a different device from the computational device, consider using setting the `experimental_io_device` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhost'.

```

What am I doing wrong?

TIA

Ullar Kask

**Comment by maciejkula** [comment]
You have to have ScaNN installed and import it before restoring the model: it brings its own custom ops and needs to be present for restore.

**Comment by Ullar-Kask** [comment]
That solved it. Thanks a lot!
