### ISSUE TITLE
Facing issue while loading ScaNN Index

### ISSUE THREAD

**Issue by aayush9400** [tensorflow/recommenders#362]
```
KeyError: 'Scann>TensorsToScann'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 906, in load_internal
    ckpt_options, filters)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 134, in __init__
    meta_graph.graph_def.library))
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 358, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 64, in function_def_to_graph
    fdef, input_shapes)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 228, in function_def_to_graph_def
    op_def = default_graph._get_op_def(node_def.op)  # pylint: disable=protected-access
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3963, in _get_op_def
    buf)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'Scann>TensorsToScann' in binary running on ip-172-30-0-56. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 152, in load
    loaded = tf_load.load_partial(path, nodes_to_load, options=options)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 775, in load_partial
    return load_internal(export_dir, tags, options, filters=filters)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 909, in load_internal
    str(err) + "\n If trying to load on a different device from the "
FileNotFoundError: Op type not registered 'Scann>TensorsToScann' in binary running on ip-172-30-0-56. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 If trying to load on a different device from the computational device, consider using setting the `experimental_io_device` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhost'.
```

**Comment by aayush9400** [comment]
Similar to #297
