### ISSUE TITLE
Not able to train DCN model with float values

### ISSUE THREAD

**Issue by meg261995** [tensorflow/recommenders#462]
I am trying to train a DCN model for LTR purpose with 2 categorical features and 3 numerical features of float type. 
Is there a way to embed float features like how we have IntergerLookup and StringLookup for int and str respectively?
I tried to pass the feature using IntegerLookup itself but I get the below error
```
Code:

tf.keras.Sequential([ tf.keras.layers.IntegerLookup(vocabulary=<float feature>, mask_token=None),
      tf.keras.layers.Embedding(len<float feature> + 1, 64)])

Error:
Error:FailedPreconditionError                   Traceback (most recent call last)
[<ipython-input-48-4c713ba09dd5>] in <module>()
      1 tf.keras.Sequential([
----> 2       tf.keras.layers.IntegerLookup(vocabulary=<feature>, mask_token=None),
      3       tf.keras.layers.Embedding(len(vocabularies[feat]) + 1, 64)])

12 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py](https://localhost:8080/#) in raise_from_not_ok_status(e, name)
   7184 def raise_from_not_ok_status(e, name):
   7185   e.message += (" name: " + name if name is not None else "")
-> 7186   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   7187 
   7188 

FailedPreconditionError: HashTable has different value for same key. Key 0 has 1 and trying to add value 2 [Op:LookupTableImportV2]
```

**Comment by patrickorlando** [comment]
Hey @meg261995,

The lookup layers can only be used for categorical features so if you're float values are continuous features you have to either:
1. Group your feature values into buckets and then use an embedding. Code sample below.
2. Scale your features with a [preprocessing layer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Normalization) before passing them on to your DCN layer.

```
from tensorflow.keras.layers import Embedding
from tensorflow.python.ops.math_ops import _bucketize as bucketize

class BucketizedEmbedding(tf.keras.layers.Layer):
    """Embedding layer based on bucketing a continuous variable."""
    def __init__(
        self,
        buckets: List[float],
        embed_dim: int,
        **kwargs) -> None:
        """Initializes the embedding layer.
        Args:
        buckets: Bucket boundaries.
        **kwargs: Extra args passed to the Keras Layer base class.
        """

        super().__init__(**kwargs)

        self.buckets = buckets
        self.embed_dim = embed_dim
        self.embedding = Embedding(len(self.buckets) + 1, self.embed_dim)

    def call(self, x: tf.Tensor) -> tf.Tensor:
        return self.embedding(bucketize(x, boundaries=self.buckets))
 ```
 
 Hope this helps.

**Comment by meg261995** [comment]
I will give this a try. Before that I tried removing Intergerlookup and kept only the embedding layer something like this. 
```  
for feat in my_float_features:
    self.embeddings[feat] = tf.keras.Sequential()
    self.embeddings[feat].add(tf.keras.layers.Embedding(len(vocabularies[feat]) + 1, embedding_dimension))
    self.embeddings[feat].compile()
 ```
Note: vocabularies[feat] is the unique set of values I have in each feature. 

With this I was able to train the model successfully. But when I reload the model in a separate session and try to predict for an input, the embedding layer of the model throws the below error. Apparently it is not able to embed negative values. 
Another catch is that if I give the same input to the model where it is trained, works fine. Negative values do not throw the error here. 

```
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-69-83daf39639c5>](https://localhost:8080/#) in <module>()
----> 1 prob = loaded({"search_term": search_terms, "products_id": product_idss,"ctr":ctrs,"feature_0":feature_0s,"feature_1":feature_1s}).numpy().flatten()
      2 prediction = dict(zip(product_idss,prob))
      3 prediction = sorted(prediction.items(),key=lambda x : x[1],reverse=True)
      4 prediction

2 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node 'embedding_12/embedding_lookup' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
      handler_func(fileobj, events)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
      self._handle_recv()
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
      self._run_callback(callback, msg)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
      callback(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
      return self.dispatch_shell(stream, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
      handler(stream, idents, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
      user_expressions, allow_stdin)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
      if self.run_code(code, result):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-5-dfd1522f1da2>", line 1, in <module>
      loaded = tf.saved_model.load(model_path_1)
Node: 'embedding_12/embedding_lookup'
indices[1] = -2 is not in [0, 8617)
	 [[{{node embedding_12/embedding_lookup}}]] [Op:__inference_restored_function_body_4316]
```

Why this behaviour?

**Comment by patrickorlando** [comment]
> Apparently it is not able to embed negative values

Correct. An embedding layer is just a matrix of size (n_categories, embed_size). It expects input as the row indexes of your categories. This is why you need some layer *before your embedding layer* which transforms your input into a consecutive set of indices.

If your feature vocab is `[4,3,78,20]`, the integer lookup layer will convert these to [2,3,4,5]. This is assuming you have 1 unknown token and 1 mask token which would be mapped to indicies `[0, 1]` respectively.

The most important thing to understand is that if your float features are actually a continuous feature, you must use either of the methods I described above. It won't make sense to treat them as categorical.

**Comment by maciejkula** [comment]
Thanks for the answer, Patrick!

**Comment by maciejkula** [comment]
@patrickorlando would you mind dropping me an email at maciejkula [at] google.com?
