### ISSUE TITLE
Candidate model generates embedding of incorrect dimensions in "Recommending movies: retrieval using a sequential model"

### ISSUE THREAD

**Issue by stephenjkaplan** [tensorflow/recommenders#487]
I'm relatively new to TensorFlow. I am currently adapting the ["Recommending movies: retrieval using a sequential model"](https://www.tensorflow.org/recommenders/examples/sequential_retrieval) TFRS tutorial to train the same model on internal data. I am debugging a broader error, but I'm particularly stuck on a detail which I think might be contributing to my broader issue.

My issue is occurring within the `compute_loss` method on the `Model`. Note that my code is identical to what's in the tutorial: 

```python
metrics = tfrs.metrics.FactorizedTopK(
  candidates=movies.batch(128).map(candidate_model)
)

task = tfrs.tasks.Retrieval(
  metrics=metrics
)

class Model(tfrs.Model):

    def __init__(self, query_model, candidate_model):
        super().__init__()
        self._query_model = query_model
        self._candidate_model = candidate_model

        self._task = task

    def compute_loss(self, features, training=False):
        watch_history = features["context_movie_id"]
        watch_next_label = features["label_movie_id"]

        query_embedding = self._query_model(watch_history)       
        candidate_embedding = self._candidate_model(watch_next_label)

        return self._task(query_embedding, candidate_embedding, compute_metrics=not training)
```

Note also that my candidate embedding model is identical to what's in the tutorial:

```python
candidate_model = tf.keras.Sequential([
  tf.keras.layers.StringLookup(
      vocabulary=unique_movie_ids, mask_token=None),
  tf.keras.layers.Embedding(len(unique_movie_ids) + 1, embedding_dimension)
])
```

The issue occurs in the line `self._candidate_model(watch_next_label)`. The output appears to have an extra dimension that it shouldn't have. I've added a `tf.print` statement within the Model definition to see what the candidate embedding looks like. The correct output (in the TFRS Colab notebook) is:

```
[[0.037503209 0.00733215734 -0.0495052226 ... -0.0271270517 0.00837401301 -0.0468932055]
 ...
 [-0.030679917 -0.00673408434 0.045563329 ... 0.00307109207 0.0214732178 -0.0421308503]]
```

However, the same `tf.print` in my code yields something like:

```
[[[-0.145804465 -0.0350196883 -0.0830400139 ... -0.0841346756 -0.072072722 -0.0654573739]]
 ...
 [[-0.0117432205 0.0256377198 -0.013333356 ... -0.0294141825 0.0264241677 -0.036734391]]]
```

Note that it is "wrapped" in a 3rd dimension. I've pretty thoroughly checked the inputs to the candidate model upon training and they are of identical dimensionality and type to those in the tutorial. I still could be missing something there but feels like I've exhausted that line of investigation. Pretty stuck here. I'm curious about how I might need to adjust the batching sizes to my data, and if that somehow has any effect on things, but am limited by my level of understanding.

Thanks for any help!

**Comment by stephenjkaplan** [comment]
for reference, my broader error is this (when running `model.evaluate()`

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-120-2113a8d1cc12> in <module>
----> 1 model.evaluate(cached_test, return_dict=True)

/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 1525, in test_function  *
        return step_function(self, iterator)
    File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 1514, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 1507, in run_step  **
        outputs = model.test_step(data)
    File "/opt/conda/lib/python3.7/site-packages/tensorflow_recommenders/models/base.py", line 88, in test_step
        loss = self.compute_loss(inputs, training=False)
    File "<ipython-input-115-61becf441d5a>", line 25, in compute_loss
        return self._task(query_embedding, candidate_embedding, compute_metrics=not training)
    File "/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "retrieval_7" (type Retrieval).
    
    in user code:
    
        File "/opt/conda/lib/python3.7/site-packages/tensorflow_recommenders/tasks/retrieval.py", line 143, in call  *
            metric_update_ops.append(
        File "/opt/conda/lib/python3.7/site-packages/tensorflow_recommenders/metrics/factorized_top_k.py", line 84, in update_state  *
            top_k_predictions, _ = self._candidates(query_embeddings, k=self._k)
        File "/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
    
        ValueError: Exception encountered when calling layer "streaming_7" (type Streaming).
        
        in user code:
        
            File "/opt/conda/lib/python3.7/site-packages/tensorflow_recommenders/layers/factorized_top_k.py", line 441, in top_k  *
                joined_scores = tf.concat([state_scores, x_scores], axis=1)
        
            ValueError: Shape must be rank 2 but is rank 3 for '{{node concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](args_0, args_2, concat/axis)' with input shapes: [?,0], [?,?,?], [].
        
        
        Call arguments received:
          • queries=tf.Tensor(shape=(None, 32), dtype=float32)
          • k=100
    
    
    Call arguments received:
      • query_embeddings=tf.Tensor(shape=(None, 32), dtype=float32)
      • candidate_embeddings=tf.Tensor(shape=(None, 1, 32), dtype=float32)
      • sample_weight=None
      • candidate_sampling_probability=None
      • candidate_ids=None
      • compute_metrics=True
```

**Comment by stephenjkaplan** [comment]
SOLVED: my issue was related to how I was loading in data to generate a vocabulary (in place of loading in data from movielens).
