### ISSUE TITLE
Validation metrics does not work

### ISSUE THREAD

**Issue by siyu1992** [tensorflow/recommenders#504]
After I added sevral features in item model, I found that validation metics seems didn't work anymore, when I call evaluation() function, overflowerror came out like this:
`model.evaluate(cached_test_new, return_dict=True)`

D:\Anaconda3\lib\site-packages\keras\utils\generic_utils.py:915: RuntimeWarning: divide by zero encountered in log10
numdigits = int(np.log10(self.target)) + 1
Traceback (most recent call last):
Debug Console, prompt 21, line 1
File "D:\Anaconda3\Lib\site-packages\keras\engine\training.py", line 1508, in evaluate
callbacks.on_test_end(logs=logs)
File "D:\Anaconda3\Lib\site-packages\keras\callbacks.py", line 523, in on_test_end
callback.on_test_end(logs)
File "D:\Anaconda3\Lib\site-packages\keras\callbacks.py", line 1043, in on_test_end
self._finalize_progbar(logs, self._test_step)
File "D:\Anaconda3\Lib\site-packages\keras\callbacks.py", line 1112, in _finalize_progbar
self.progbar.update(self.target, list(logs.items()), finalize=True)
File "D:\Anaconda3\Lib\site-packages\keras\utils\generic_utils.py", line 915, in update
numdigits = int(np.log10(self.target)) + 1
builtins.OverflowError: cannot convert float infinity to integer

I set validation_freq=5, and validation result didn't come out,

`one_layer_history = model.fit(
    cached_train,
    validation_data=cached_test,
    validation_freq=5,
    epochs=num_epochs,
    verbose=2)`

training log:

Epoch 1/100
538/538 - 89s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 831.6680 - regularization_loss: 0.0000e+00 - total_loss: 831.6680
2022-06-15 11:02:11.931192: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 598652 of 1300000

2022-06-15 11:02:21.931221: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1220326 of 1300000
2022-06-15 11:02:22.928548: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:02:22.928639: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:02:22.928678: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000
2022-06-15 11:02:31.916545: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1002299 of 1100000
2022-06-15 11:02:32.813994: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 2/100
538/538 - 87s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 618.5934 - regularization_loss: 0.0000e+00 - total_loss: 618.5934
2022-06-15 11:03:39.152672: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 615275 of 1300000
2022-06-15 11:03:49.152666: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1262972 of 1300000
2022-06-15 11:03:49.431177: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:03:49.431257: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:03:49.431288: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000

2022-06-15 11:03:59.122842: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1061253 of 1100000
2022-06-15 11:03:59.448307: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 3/100
538/538 - 86s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 560.5813 - regularization_loss: 0.0000e+00 - total_loss: 560.5813

2022-06-15 11:05:05.958832: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 591211 of 1300000
2022-06-15 11:05:15.958853: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1196708 of 1300000
2022-06-15 11:05:17.341993: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:05:17.342106: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:05:17.342144: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000
2022-06-15 11:05:25.935150: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 964929 of 1100000
2022-06-15 11:05:27.165711: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 4/100
538/538 - 90s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 424.9323 - regularization_loss: 0.0000e+00 - total_loss: 424.9323

2022-06-15 11:06:36.149934: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 609622 of 1300000
2022-06-15 11:06:46.149923: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1239039 of 1300000
2022-06-15 11:06:46.833334: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:06:46.833443: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:06:46.833479: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000
2022-06-15 11:06:56.121954: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1096117 of 1100000
2022-06-15 11:06:56.152681: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 5/100
538/538 - 86s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 431.3773 - regularization_loss: 0.0000e+00 - total_loss: 431.3773
2022-06-15 11:08:02.034184: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 607006 of 1300000

2022-06-15 11:08:12.034193: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1253334 of 1300000
2022-06-15 11:08:12.457339: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:08:12.457416: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:08:12.457442: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000
2022-06-15 11:08:21.312703: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 6/100
538/538 - 87s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 366.8698 - regularization_loss: 0.0000e+00 - total_loss: 366.8698
2022-06-15 11:09:29.537571: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 619384 of 1300000

2022-06-15 11:09:39.537576: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1250191 of 1300000
2022-06-15 11:09:40.017937: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:09:40.018015: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:09:40.018040: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000
2022-06-15 11:09:48.975790: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 7/100
538/538 - 85s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 419.2379 - regularization_loss: 0.0000e+00 - total_loss: 419.2379
2022-06-15 11:10:54.565280: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 628766 of 1300000
2022-06-15 11:11:04.565294: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1277466 of 1300000
2022-06-15 11:11:04.613453: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:11:04.613515: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:11:04.613543: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000

2022-06-15 11:11:13.441545: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 8/100
538/538 - 82s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 347.8752 - regularization_loss: 0.0000e+00 - total_loss: 347.8752

2022-06-15 11:12:16.618079: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 620171 of 1300000
2022-06-15 11:12:26.618080: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1269764 of 1300000
2022-06-15 11:12:26.784855: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:12:26.784925: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:12:26.784949: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000
2022-06-15 11:12:35.617281: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 9/100
538/538 - 84s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 342.1136 - regularization_loss: 0.0000e+00 - total_loss: 342.1136
2022-06-15 11:13:40.884774: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 614733 of 1300000

2022-06-15 11:13:50.884778: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1243609 of 1300000
2022-06-15 11:13:51.492446: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:13:51.492527: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:13:51.492555: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000
2022-06-15 11:14:00.595935: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

Epoch 10/100
538/538 - 84s - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 308.5079 - regularization_loss: 0.0000e+00 - total_loss: 308.5079
2022-06-15 11:15:04.863001: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 618047 of 1300000
2022-06-15 11:15:14.862998: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1242188 of 1300000
2022-06-15 11:15:15.466929: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.
2022-06-15 11:15:15.467019: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1 of 1100000
2022-06-15 11:15:15.467053: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 2 of 1100000

2022-06-15 11:15:24.839508: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1037320 of 1100000
2022-06-15 11:15:25.376921: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.

When I call model.evaluate(cached_test_new, return_dict=True):

Traceback (most recent call last):
  File "trfs_jinke_data_recall_deep_training_add_ee_item_features.py", line 549, in <module>
    model.evaluate(cached_test_new, return_dict=True)
  File "/home/user1/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/engine/training.py", line 1508, in evaluate
    callbacks.on_test_end(logs=logs)
  File "/home/user1/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/callbacks.py", line 523, in on_test_end
    callback.on_test_end(logs)
  File "/home/user1/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/callbacks.py", line 1043, in on_test_end
    self._finalize_progbar(logs, self._test_step)
  File "/home/user1/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/callbacks.py", line 1112, in _finalize_progbar
    self.progbar.update(self.target, list(logs.items()), finalize=True)
  File "/home/user1/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 915, in update
    numdigits = int(np.log10(self.target)) + 1
OverflowError: cannot convert float infinity to integer

**Comment by SergheiDinu** [comment]
Drop this to be able to see accuracy in training time! 
![image](https://user-images.githubusercontent.com/60985084/174954248-c8f0b992-e311-44d0-8672-18a674aa802f.png)
