### ISSUE TITLE
How to generate predictions using "Building deep retrieval models" tutorial with side features in candidate tower

### ISSUE THREAD

**Issue by kingjosephm** [tensorflow/recommenders#586]
Hi,

I'm following the tutorial "Building deep retrieval models" and seem to have encountered a slightly different, though related issue than either [this post](https://github.com/tensorflow/recommenders/issues/226) or this [other one](https://github.com/tensorflow/recommenders/issues/162) on this same tutorial. The main difference is that I'm including a side feature in the candidate tower, which I suspect is causing the problem. Thanks for your help in advance!

The data I'm using are click data from a website, organized like this:

    user product  timestamp
    1       a      58552
    2       b      63968
    3       c      57069

Training data (see below) look like this:

    <TensorSliceDataset element_spec={'user': TensorSpec(shape=(), dtype=tf.string, name=None), 'product': TensorSpec(shape=. (), dtype=tf.string, name=None), 'timestamp': TensorSpec(shape=(), dtype=tf.int64, name=None)}>

The architecture of the model follows the tutorial, though with some modifications (some portions are omitted for simplification):

    import tempfile
    import numpy as np
    import pandas as pd
    import tensorflow as tf
    import tensorflow_recommenders as tfrs
    from recommender.processors import UserProductData
    import json
    import argparse
    import matplotlib.pyplot as plt
    from typing import Dict, Text, Union
    from keras.regularizers import l2

    class UserModel(tf.keras.Model):
    
        def __init__(self, embedding_dims: int = 64, features: tuple = ()):
            """ Model for user embeddings & user features
    
            Args:
                embedding_dims: int, number of user embedding vectors
                features: tuple,features to include in model
            """
            super().__init__()
            self.embedding_dims = embedding_dims
            self.feature_embeddings = {}
            time_embeddings_dim = 8
    
            # User embedding layer
            self.user_embedding = tf.keras.Sequential([
                tf.keras.layers.StringLookup(
                    vocabulary=unique_users, mask_token=None),
                tf.keras.layers.Embedding(len(unique_users) + 1, self.embedding_dims)
            ])
    
            # Time layers
            if "timestamp" in features:
                normalized_timestamp = tf.keras.layers.Normalization(axis=None)
                normalized_timestamp.adapt(timestamps)
                self.feature_embeddings['timestamp'] = tf.keras.Sequential([
                    normalized_timestamp, tf.keras.layers.Reshape([1])
                ])
    
        def call(self, inputs) -> tf.Tensor:
            return tf.concat([self.user_embedding(inputs['user'])] +
                             [self.feature_embeddings[k](inputs[k]) for k in self.feature_embeddings],
                             axis=1)

    class ProductModel(tf.keras.Model):
    
        def __init__(self, embedding_dims: int = 64, features: tuple = ()):
            """ Model for product embeddings & product features
    
            Args:
                embedding_dims, int, number of product embedding vectors
                features: tuple, features to include in model
            """
            super().__init__()
            self.embedding_dims = embedding_dims
            self.feature_embeddings = {}
            time_embeddings_dim = 8
    
            self.product_embedding = tf.keras.Sequential([
                tf.keras.layers.StringLookup(
                    vocabulary=uniq_products, mask_token=None),
                tf.keras.layers.Embedding(len(uniq_products) + 1, self.embedding_dims)
                # tf.keras.layers.Lambda(lambda x: tf.math.reduce_mean(x, axis=1)
            ])
    
            # Time layers
            if "timestamp" in features:
                normalized_timestamp = tf.keras.layers.Normalization(axis=None)
                normalized_timestamp.adapt(timestamps)
                self.feature_embeddings['timestamp'] = tf.keras.Sequential([
                    normalized_timestamp, tf.keras.layers.Reshape([1])
                ])
            
        def call(self, inputs) -> tf.Tensor:
            return tf.concat([self.product_embedding(inputs['product'])] +
                             [self.feature_embeddings[k](inputs[k]) for k in self.feature_embeddings],
                             axis=1)

    class ModelStack(tf.keras.Model):
    
        def __init__(self, embedding_model: Union[UserModel, ProductModel], layer_sizes: list = [64, 32],
                     l2_regularization: float = 0.0):
            """Model stack for user or product model
    
            Args:
                embedding_model, instance of a class, either User or Product model class
                layer_sizes: A list of integers where the i-th entry represents the number of units the i-th layer contains
                l2_regularization: float, l2 regularization term to apply to kernel_regularizer dense layers, values should
                    range between 0-0.1.
            """
            super().__init__()
    
            # Initialize user model for embeddings
            self.embedding_model = embedding_model
    
            # Initialize model to add layers
            self.dense_layers = tf.keras.Sequential()
    
            assert (layer_sizes), "`config['layer_sizes']` cannot be empty list! Please ensure at least one layer is specified"
    
            # Use the ReLU activation for all but the last layer
            if len(layer_sizes) > 1:
                for layer_size in layer_sizes[:-1]:
                    self.dense_layers.add(tf.keras.layers.Dense(layer_size, activation="relu",
                                                                kernel_regularizer=l2(l2_regularization)))
    
            # Linear activation for last layer
            self.dense_layers.add(tf.keras.layers.Dense(layer_sizes[-1], kernel_regularizer=l2(l2_regularization)))
    
        def call(self, inputs) -> tf.Tensor:
            feature_embedding = self.embedding_model(inputs)
            return self.dense_layers(feature_embedding)

    class RetrievalModel(tfrs.models.Model):
    
        def __init__(self, user_features: tuple = (), product_features: tuple = (), layer_sizes: list = [64, 32],
                     embedding_dims: int = 64, l2_regularization: float = 0.0):
            """ Combined retrieval model, containing both query and candidate models
    
            Args:
                user_features: tuple, features to include in user model
                product_features: tuple, features to include in product model
                layer_sizes: A list of integers where the i-th entry represents the number of units the i-th layer contains
                embedding_dims: int, number of product and user embedding vectors
                l2_regularization: float, l2 regularization term to apply to kernel_regularizer dense layers, values should
                    range between 0-0.1.
            """
            super().__init__()
            self.user_features = user_features
            self.product_features = product_features
            self.user_model = UserModel(embedding_dims, self.user_features)
            self.product_model = ProductModel(embedding_dims, self.product_features)
    
            self.query_model = ModelStack(self.user_model, layer_sizes, l2_regularization)
            self.candidate_model = ModelStack(self.product_model, layer_sizes,  l2_regularization)
    
            self.task = tfrs.tasks.Retrieval(
                metrics=tfrs.metrics.FactorizedTopK(
                    candidates=(train.apply(tf.data.experimental.dense_to_ragged_batch(128))
                                .map(self.candidate_model)), ks=[1, 5, 10, 50]
                ),
            )

        def compute_loss(self, inputs: Dict[Text, tf.Tensor], training: bool = False) -> tf.Tensor:
            """
            Calculates loss for epoch
            :param inputs: dict, containing tf.Tensors
            :param training: bool, necessary for tf.keras.Model, not used
            :return: tf.Tensor
            """
            query_embeddings = self.query_model({
                'user': inputs['user'],
                **{k: inputs[k] for k in self.user_features if k in self.user_features}
            })
            candidate_embeddings = self.candidate_model({
                'product': inputs['product'],
                **{k: inputs[k] for k in self.product_features if k in self.product_features}
            })
    
            return self.task(query_embeddings, candidate_embeddings)

    if __name__ == '__main__':

    train, val, test, config = some_function()
    uniq_products = np.unique(np.concatenate(list(train.batch(1_000).map(lambda x: x['product'])))).astype(str)
    unique_users = np.unique(np.concatenate(list(train.batch(1_000).map(lambda x: x['user']))))
    timestamps = np.unique(np.concatenate(list(train.batch(1_000).map(lambda x: x['timestamp']))))

    model = RetrievalModel(user_features=tuple(config['user_features']), product_features=tuple(config['product_features']),
                           layer_sizes=config['layer_sizes'], embedding_dims=config['embedding_dims'],
                           l2_regularization=config['l2_regularization'])
    model.compile(optimizer=tf.keras.optimizers.Adam(config['learn_rate']), run_eagerly=True)
    early_stopping = tf.keras.callbacks.EarlyStopping(patience=config['patience'],
                                                      restore_best_weights=True)

    # Convert to tf.BatchDataset
    train_b = train.shuffle(100_000).batch(config['batch_size'])
    val_b = val.shuffle(100_000).batch(config['batch_size'])
    test_b = test.shuffle(100_000).batch(config['batch_size'])

    # Train model
    history = model.fit(
        train_b,
        validation_data=val_b,
        validation_freq=1,
        epochs=config['max_epochs'],
        verbose=config['verbose'],
        callbacks=early_stopping
    )

    # Select first observation in training set to generate predictions
    for x in train.take(1).as_numpy_iterator():
        user_details = {key: np.array([val]) for (key, val) in x.items() if key in ['user']+config['user_features']}
        product_details = {key: np.array([val]) for (key, val) in x.items() if key in ['product']+config['product_features']}

This is what `user_details` looks like:

    {'user': array([b'1'], dtype='|S9'), 'timestamp': array([58552])}

Note

    # model.query_model(user_details)  # note - this works fine
    # model.candidate_model(product_details)  # note - this works fine too
    
Error source

    index = tfrs.layers.factorized_top_k.BruteForce(model.query_model)
    index.index_from_dataset(train_b.map(model.candidate_model))
    _, titles = index(model.query_model(user_details))

Traceback

    Traceback (most recent call last):
      File "/opt/anaconda3/envs/bm_ds_recommender/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-2-3c0f4436a89b>", line 3, in <module>
        _, titles = index(model.query_model(user_details))
      File "/opt/anaconda3/envs/bm_ds_recommender/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
      File "/opt/anaconda3/envs/bm_ds_recommender/lib/python3.10/site-packages/tensorflow_recommenders/layers/factorized_top_k.py", line 584, in call
        queries = self.query_model(queries)
      File "<>/recommender/retrieval.py", line 183, in call
        feature_embedding = self.embedding_model(inputs)
      File "<>/recommender/retrieval.py", line 80, in call
        return tf.concat([self.user_embedding(inputs['user'])] +
    TypeError: Exception encountered when calling layer "user_model" (type UserModel).
    Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got 'user'
    Call arguments received by layer "user_model" (type UserModel):
      • inputs=tf.Tensor(shape=(1, 32), dtype=float32)

**Comment by patrickorlando** [comment]
You've got a couple of errors in your implementation.

1. Not indexing the model correctly. `index_from_dataset` expects a tuple of `(item_id, item_embedding)`.
From the [tutorial](https://www.tensorflow.org/recommenders/examples/efficient_serving#approximate_prediction):
```python
brute_force = tfrs.layers.factorized_top_k.BruteForce(model.user_model)
brute_force.index_from_dataset(
    movies.batch(128).map(lambda title: (title, model.movie_model(title)))
)
```

2. Applying the query model twice. You passed the query model to the BruteForce layer's init method. 
https://github.com/tensorflow/recommenders/blob/2ac1483671dc33c0ff1800a4a5f70f7dd20c7471/tensorflow_recommenders/layers/factorized_top_k.py#L504-L517

```python
_, titles = index(model.query_model(user_details)) # <--------- 
_, titles = index(user_details)                    # <------ should be this
```

hope this helps!

**Comment by kingjosephm** [comment]
Thanks, yeah that was a dumb error on my part. Based on your comments the following code runs:

```
  index = tfrs.layers.factorized_top_k.BruteForce(model.query_model)
  index.index_from_dataset(train_b.map(model.candidate_model))
  _, title = index(user_details)  # <-- Returns: Tuple(top candidate scores, top candidate identifiers)
```

However, I'm uncertain what the "top candidate identifiers" (how it's explained on the [website](https://www.tensorflow.org/recommenders/api_docs/python/tfrs/layers/factorized_top_k/BruteForce)) pertain to if there are other features in the candidate tower? Do I need to change something in order to ensure the predictions correspond to item IDs (products in my case)?

It seems the `BruteForce` method expects all of the same features provided to the candidate tower in order to make predictions, which makes sense.

**Comment by zeroonesfas** [comment]
@kingjosephm Hello, thanks for your sharing
I got following error when I run your last code block. Do you know why ?

----> 1 uniq_products = np.unique(np.concatenate(list(user.batch(1_000).map(lambda x: x['product'])))).astype(str)
      2 uniq_products = tf.data.Dataset.from_tensor_slices({'product': uniq_products})
      4 index = tfrs.layers.factorized_top_k.BruteForce(model.query_model)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

**Comment by kartik-awasthi-IAGL** [comment]
How do I run this for multiple users? I got it working for 1 user. But if I gave to run it a MapDataset with all users i get an error. Any ideas?
