### ISSUE TITLE
[Question] Loss isn't decreasing when adding meta features to the candidate models

### ISSUE THREAD

**Issue by OmarMAmin** [tensorflow/recommenders#609]
Hi Team,

I'm trying to add features to the candidate model (constant features per candidate id)
my dataset looks like the following
```
chain_id account_id tlabel_str
    a          b    'healthy brazillian salad'       
```

My code is as follows
```python
class chainModel(tf.keras.Model):
    def __init__(self, chain_emb_size, cuisine_emb_size, unique_chain_ids_str, cuisines):
        super().__init__()

        max_tokens = 75 ## unique cuisines are 75

        self.chain_embedding = tf.keras.Sequential([
          tf.keras.layers.StringLookup(
              vocabulary=unique_chain_ids_str, mask_token=None, name='chain_lookup'),
          tf.keras.layers.Embedding(len(unique_chain_ids_str) + 1, chain_emb_size,
                                    name ='chain_embedding')
        ])

        self.cuisine_vectorizer = tf.keras.layers.TextVectorization(
            max_tokens=max_tokens, name='Vectorizer')

        self.cuisine_text_embedding = tf.keras.Sequential([
          self.cuisine_vectorizer,
          tf.keras.layers.Embedding(max_tokens, cuisine_emb_size, mask_zero=True, name='cuisine_embedding'),
          tf.keras.layers.GlobalAveragePooling1D(),
        ])

        self.cuisine_vectorizer.adapt(cuisines)

    def call(self, chains_df):

        output = tf.concat([
            self.chain_embedding(chains_df['chain_id']),
            self.cuisine_text_embedding(chains_df['tlabel_str']),
        ], axis=1)
        return output


def create_two_tower_model(embedding_dimension, negative_samples, unique_customer_ids_str,
                           unique_chain_ids_str, cuisines, chains):

    customer_model = tf.keras.Sequential([
        tf.keras.layers.StringLookup(
            vocabulary=unique_customer_ids_str, mask_token=None),
        tf.keras.layers.Embedding(len(unique_customer_ids_str) + 1, embedding_dimension),
        tf.keras.layers.Dense(embedding_dimension, activation='relu')
    ])
    chain_model = tf.keras.Sequential([
        chainModel(chain_emb_size=embedding_dimension, cuisine_emb_size=embedding_dimension,
                   unique_chain_ids_str= unique_chain_ids_str, cuisines= cuisines),
        tf.keras.layers.Dense(embedding_dimension, activation='relu')
    ])
    model = AccountChainModel(customer_model, chain_model, negative_samples, chains=chains)
    model.compile(optimizer=tf.keras.optimizers.Adam())

    return model


class AccountChainModel(tfrs.Model):

    def __init__(self, customer_model, chain_model, negatives_samples, chains):
        super().__init__()
        self.chain_model: tf.keras.Model = chain_model
        self.customer_model: tf.keras.Model = customer_model
        self.task = tfrs.tasks.Retrieval(
            metrics=tfrs.metrics.FactorizedTopK(
                candidates=chains.batch(negatives_samples).map(self.chain_model)),
        )

    def compute_loss(self, features, training=False):
        customer_embeddings = self.customer_model(features["account_id"])
        chain_embeddings = self.chain_model({
            "chain_id": features["chain_id"],
            "tlabel_str": features['tlabel_str']})
        return self.task(customer_embeddings, chain_embeddings ,compute_metrics=not training)


unique_chains_df = train_df[['chain_id', 'tlabel_str']].drop_duplicates()

chains_ds = tf.data.Dataset.from_tensor_slices(dict(unique_chains_df))
cuisines = train_df.tlabel_str.unique()
chains = chains_ds.map(lambda x: {'chain_id': x['chain_id'], 'tlabel_str': x['tlabel_str']})
train_ds = tf.data.Dataset.from_tensor_slices(
    dict(self.train_df[['account_id', 'chain_id', 'tlabel_str']])).shuffle(100_000).batch(8192)  # .cache()

embedding_dimension = 16
num_epochs = 40
negative_samples = 8

callbacks = []
model = create_two_tower_model(embedding_dimension=embedding_dimension,
                               negative_samples=negative_samples,
                               unique_customer_ids_str=self.unique_customer_ids_str,
                               unique_chain_ids_str=self.unique_chain_ids_str,
                               cuisines=cuisines, chains=chains)

history = model.fit(train_ds, epochs=num_epochs, verbose=1)
```

The problem is that when i write the same code without other features in the candidate model, the loss is decreasing and i can see that the model learnt good semantic relation between the two different entities, but with adding the additional features the model loss isn't decreasing, it's the same for each epoch, and I'm not sure what I'm doing wrong.

It'd be great if you can release a tutorial for chain model with context features, the only one available is this tutorial
https://www.tensorflow.org/recommenders/examples/context_features
But it only use the same feature --> movie title, but sending the same string into different layers (direct embedding layer and another text embedding layer), I believe my problem might be in how I'm generating the candidates, or the model isn't connected for some reason.

Thanks for your support, and please let me know if i need to provide any additional information, or if you know the most probable reason, and I'll investigate.

**Comment by OmarMAmin** [comment]
I tried the tutorial here, to double check if there's sth wrong with my code
https://www.tensorflow.org/recommenders/examples/context_features

and when i tried it on GPU it didn't work throwing the following error
```shell
Metal device set to: Apple M1 Pro

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

2023-01-23 13:35:49.173211: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-01-23 13:35:49.173334: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-01-23 13:35:49.279815: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-01-23 13:35:55.021533: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Traceback (most recent call last):
  File "/Users/omar.mohamed.2/PyCharmProjects/TwoTowerModel/src/train_two_tower_with_features_movies.py", line 159, in <module>
    model = MovielensModel(use_timestamps=False)
  File "/Users/omar.mohamed.2/PyCharmProjects/TwoTowerModel/src/train_two_tower_with_features_movies.py", line 32, in __init__
    MovieModel(),
  File "/Users/omar.mohamed.2/PyCharmProjects/TwoTowerModel/src/train_two_tower_with_features_movies.py", line 78, in __init__
    self.title_vectorizer.adapt(movies)
  File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/keras/layers/preprocessing/text_vectorization.py", line 467, in adapt
    super().adapt(data, batch_size=batch_size, steps=steps)
  File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/keras/engine/base_preprocessing_layer.py", line 258, in adapt
    self._adapt_function(iterator)
  File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:

Detected at node 'StringSplit/stack' defined at (most recent call last):
    File "/Users/omar.mohamed.2/PyCharmProjects/TwoTowerModel/src/train_two_tower_with_features_movies.py", line 159, in <module>
      model = MovielensModel(use_timestamps=False)
    File "/Users/omar.mohamed.2/PyCharmProjects/TwoTowerModel/src/train_two_tower_with_features_movies.py", line 32, in __init__
      MovieModel(),
    File "/Users/omar.mohamed.2/PyCharmProjects/TwoTowerModel/src/train_two_tower_with_features_movies.py", line 78, in __init__
      self.title_vectorizer.adapt(movies)
    File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/keras/layers/preprocessing/text_vectorization.py", line 467, in adapt
      super().adapt(data, batch_size=batch_size, steps=steps)
    File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/keras/engine/base_preprocessing_layer.py", line 258, in adapt
      self._adapt_function(iterator)
    File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/keras/engine/base_preprocessing_layer.py", line 123, in adapt_step
      self.update_state(data)
    File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/keras/layers/preprocessing/text_vectorization.py", line 470, in update_state
      self._lookup_layer.update_state(self._preprocess(data))
    File "/Users/omar.mohamed.2/miniforge3/envs/tfm2/lib/python3.9/site-packages/keras/layers/preprocessing/text_vectorization.py", line 575, in _preprocess
      inputs = tf.strings.split(inputs)
Node: 'StringSplit/stack'
2 root error(s) found.
  (0) NOT_FOUND:  No registered 'ExpandDims' OpKernel for 'GPU' devices compatible with node {{node StringSplit/stack}}
         (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_STRING, Tdim=DT_INT32, _XlaHasReferenceVars=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"
        .  Registered:  device='XLA_CPU_JIT'; Tdim in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, 16005131165644881776, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]
  device='DEFAULT'; T in [DT_HALF]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_HALF]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_BFLOAT16]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_BFLOAT16]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_FLOAT]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_FLOAT]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_DOUBLE]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_DOUBLE]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_UINT64]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_UINT64]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_INT64]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_INT64]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_UINT32]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_UINT32]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_UINT16]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_UINT16]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_INT16]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_INT16]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_UINT8]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_UINT8]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_INT8]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_INT8]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_COMPLEX64]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_COMPLEX64]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_COMPLEX128]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_COMPLEX128]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_BOOL]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_BOOL]; Tdim in [DT_INT64]
  device='DEFAULT'; T in [DT_INT32]; Tdim in [DT_INT32]
  device='DEFAULT'; T in [DT_INT32]; Tdim in [DT_INT64]
  device='CPU'; Tdim in [DT_INT32]
  device='CPU'; Tdim in [DT_INT64]

         [[StringSplit/stack]]
  (1) CANCELLED:  Function was cancelled before it was started
0 successful operations.
0 derived errors ignored. [Op:__inference_adapt_step_1584]
```

When I switched to CPU it worked fine, but for my case it's still not working not sure why on CPU the loss is nan 
On GPU my code doesn't optimize the loss, it's consistently around 73412 loss value and doesn't decrease, unlike the tutorial which throws an error on the GPU

**Comment by OmarMAmin** [comment]
closing this, the error was fixed when i provided the vocabulary in the textvectorization layer without the adapt function, as i believe it's not implemented yet in m1
