### ISSUE TITLE
Tensorboard error when using quickstart model

### ISSUE THREAD

**Issue by tszumowski** [tensorflow/recommenders#94]
I was able to get the [Quickstart](https://www.tensorflow.org/recommenders/examples/quickstart) model running seamlessly. 

However, I then tried to add a Tensorboard callback, by following the [Tensorboard Quickstart](https://www.tensorflow.org/tensorboard/get_started).

In the [tfrs API docs](https://www.tensorflow.org/recommenders/api_docs/python/tfrs/models/Model), it says:
    
> Note that this base class is a thin conveniece wrapper for tf.keras.Model.

Since it is a Keras model, I followed this section: [Using TensorBoard with Keras Model.fit()](https://www.tensorflow.org/tensorboard/get_started#using_tensorboard_with_keras_modelfit)

This means I replaced this line in Quickstart:
```python
model.fit(ratings.batch(4096), epochs=3)
```

with these lines:
```python
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(ratings.batch(4096), epochs=3, callbacks=[tensorboard_callback])
```

_(in other words, adding the `callbacks=` input argument`)_

When I run this, I get the following error:

```
 2/25 [=>............................] - ETA: 9s - factorized_top_k: 7.5684e-04 - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 3.6621e-04 - factorized_top_k/top_100_categorical_accuracy: 0.0034 - loss: 34084.4688 - regularization_loss: 0.0000e+00 - total_loss: 34084.4688    WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.2553s vs `on_train_batch_end` time: 0.6103s). Check your callbacks.
WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.2553s vs `on_train_batch_end` time: 0.6103s). Check your callbacks.
25/25 [==============================] - ETA: 0s - factorized_top_k: 0.0293 - factorized_top_k/top_1_categorical_accuracy: 6.0000e-05 - factorized_top_k/top_5_categorical_accuracy: 0.0014 - factorized_top_k/top_10_categorical_accuracy: 0.0047 - factorized_top_k/top_50_categorical_accuracy: 0.0424 - factorized_top_k/top_100_categorical_accuracy: 0.0978 - loss: 33915.1966 - regularization_loss: 0.0000e+00 - total_loss: 33915.1966Traceback (most recent call last):
  File "tfrs_quickstart.py", line 100, in <module>
    model.fit(ratings.batch(4096), epochs=3, callbacks=[tensorboard_callback])
  File "/home/temp/.venv/tfrs/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/temp/.venv/tfrs/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/temp/.venv/tfrs/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 412, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/temp/.venv/tfrs/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 2182, in on_epoch_end
    self._log_weights(epoch)
  File "/home/temp/.venv/tfrs/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 2233, in _log_weights
    weight_name = weight.name.replace(':', '_')
AttributeError: 'TrackableWeightHandler' object has no attribute 'name'
```

**Should this work as-is with `.fit()`? Or do I need to make a custom implementation (as described at the top [here](https://www.tensorflow.org/recommenders/api_docs/python/tfrs/models/Model))?** 

I did notice the `tfrs.models.Model` uses [`tf.GradientTape()`](https://github.com/tensorflow/recommenders/blob/1653110aded484a4f497afa83cd6c5e94574df59/tensorflow_recommenders/models/base.py#L66), and the Tensorboard docs have [different directions](https://www.tensorflow.org/tensorboard/get_started#using_tensorboard_with_other_methods) for trainers that use that method. 

I also attached the `.py` file representation of the quickstart for reference (where the lines are added from above)

[tfrs_quickstart.py.txt](https://github.com/tensorflow/recommenders/files/5314719/tfrs_quickstart.py.txt)

**Comment by tszumowski** [comment]
## Update
When I remove `histogram_freq`, everything works fine.
```
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir)
```

I do not currently have a need to view weight/activation histograms. So that is fine for me, and I'm happy to close this ticket. Though if you'd like to leave this issue open to address otherwise, it can remain open.

**Comment by maciejkula** [comment]
Thanks for the debugging! We should probably look into adding a battery of tests that include TensorBoard integration.

**Comment by windmaple** [comment]
TB is working fine now.

**Comment by TimSchmeier** [comment]
Not sure if this lib is still under active development but when adding `histogram_freq=1` to the tensorboard callback there is still an issue:

```ERROR 2025-03-12T20:48:45.903217227Z [resource.labels.taskName: workerpool0-0] File "/usr/local/lib/python3.9/dist-packages/tensorboard/plugins/histogram/summary_v2.py", line 225, in _buckets
ERROR 2025-03-12T20:48:45.903225305Z [resource.labels.taskName: workerpool0-0] data = tf.cast(data, tf.float64)
ERROR 2025-03-12T20:48:45.903233652Z [resource.labels.taskName: workerpool0-0] tensorflow.python.framework.errors_impl.UnimplementedError: {{function_node __wrapped__Cast_device_/job:localhost/replica:0/task:0/device:CPU:0}} Cast string to double is not supported [Op:Cast] name:
```

using these tensorflow lib versions:
```
tensorboard==2.13.0
tensorboard-data-server==0.7.2
tensorflow==2.13.0
tensorflow-data-validation==1.14.0
tensorflow-datasets==4.9.3
tensorflow-estimator==2.13.0
tensorflow-hub==0.13.0
tensorflow-io-gcs-filesystem==0.37.1
tensorflow-metadata==1.14.0
tensorflow-model-analysis==0.45.0
tensorflow-model-optimization==0.8.0
tensorflow-ranking==0.5.5
tensorflow-recommenders==0.7.3
tensorflow-serving-api==2.13.0
tensorflow-text==2.13.0
tensorflow-transform==1.14.0
```

**Comment by TimSchmeier** [comment]
To add more details, I could not reproduce this error on CPU so it appears to manifest only when using GPUs.
